services:
  smartquotebot:
    image: thomas934/smart-quote-bot:latest
    container_name: smartquotebot
    environment:
      # Bot config
      - BOT__TOKEN=${BOT__TOKEN}
      - BOT__COMMAND_PREFIX=${BOT__COMMAND_PREFIX}

      # Sentry
      - SENTRY__ENABLE=${SENTRY__ENABLE}
      - SENTRY__DSN=${SENTRY__DSN}
      - SENTRY__SEND_PII=${SENTRY__SEND_PII}
      - SENTRY__TRACES_SAMPLE_RATE=${SENTRY__TRACES_SAMPLE_RATE}
      - SENTRY__PROFILING_SAMPLE_RATE=${SENTRY__PROFILING_SAMPLE_RATE}

      # Paths
      - PATHS__DATA_DIR=${PATHS__DATA_DIR}
      - PATHS__LOGS_DIR=${PATHS__LOGS_DIR}
      - PATHS__QUOTES_FILE=${PATHS__QUOTES_FILE}
      - PATHS__QUOTES_INDEX_FILE=${PATHS__QUOTES_INDEX_FILE}

      # AI
      - AI__EMBEDDING_MODEL=${AI__EMBEDDING_MODEL}
    restart: unless-stopped
