services:
  rodofbot:
    build:
      context: .
      target: dev
    image: thomas934/smart-quote-bot:feat-introduce-uv
    volumes:
      - ./src:/app/src
    working_dir: /app
    environment:
      # Runtime environment
      - ENV=development
      - PYTHONPATH=/app/src

      # Bot config
      - BOT__TOKEN=${BOT__TOKEN}
      - BOT__COMMAND_PREFIX=${BOT__COMMAND_PREFIX}

      # Sentry
      - SENTRY__ENABLE=${SENTRY__ENABLE}
      - SENTRY__DSN=${SENTRY__DSN}
      - SENTRY__SEND_PII=${SENTRY__SEND_PII}
      - SENTRY__TRACES_SAMPLE_RATE=${SENTRY__TRACES_SAMPLE_RATE}
      - SENTRY__PROFILING_SAMPLE_RATE=${SENTRY__PROFILING_SAMPLE_RATE}

      # Paths
      - PATHS__DATA_DIR=${PATHS__DATA_DIR}
      - PATHS__LOGS_DIR=${PATHS__LOGS_DIR}
      - PATHS__QUOTES_FILE=${PATHS__QUOTES_FILE}
      - PATHS__QUOTES_INDEX_FILE=${PATHS__QUOTES_INDEX_FILE}

      # AI
      - AI__EMBEDDING_MODEL=${AI__EMBEDDING_MODEL}
    command: ["python", "-m", "smartquotebot.bot"]
